// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function from(prim0, prim1) {
  return Buffer.from(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function toString(prim0, prim1) {
  return prim0.toString(prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

export {
  from ,
  toString ,
}
/* No side effect */
