// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Index from "./index";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function cn(prim) {
  return Caml_splice_call.spliceApply(Index.cn, [prim]);
}

export {
  cn ,
}
/* ./index Not a pure module */
