// Generated by ReScript, PLEASE EDIT WITH CARE


var selectionBoxStroke = "blue";

var selectionBoxFill = "rgba(38, 132, 255, 0.3)";

var selectionBoxLineWidth = 1;

var elementStroke = "black";

var elementLineWidth = 1;

var selectedElementStroke = "blue";

var rectFill = "rgba(97, 97, 97, 0.1)";

var selectedRectFill = "rgba(38, 132, 255, 0.1)";

var font = "16px Arial";

export {
  selectionBoxStroke ,
  selectionBoxFill ,
  selectionBoxLineWidth ,
  elementStroke ,
  elementLineWidth ,
  selectedElementStroke ,
  rectFill ,
  selectedRectFill ,
  font ,
}
/* No side effect */
