// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";

var defaultStyle = {
  lineWidth: 1
};

function getStyle(tool) {
  var match = tool.engine;
  if (typeof match !== "object") {
    return ;
  } else {
    return {
            lineWidth: match._0.lineWidth
          };
  }
}

function getOptStyleWithDefaults(tool) {
  var style = Core__Option.flatMap(tool, getStyle);
  if (style !== undefined) {
    return style;
  } else {
    return defaultStyle;
  }
}

function getLineWidth(style) {
  return Core__Option.getOr(style.lineWidth, 1);
}

export {
  getOptStyleWithDefaults ,
  getLineWidth ,
}
/* No side effect */
