// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as Canvas__Style from "./Canvas__Style.bs.js";

var defaultStyle = {
  lineWidth: Canvas__Style.elementLineWidth
};

function getStyle(tool) {
  var match = tool.engine;
  if (typeof match !== "object") {
    return ;
  } else {
    return {
            lineWidth: match._0.lineWidth
          };
  }
}

function getOptStyleWithDefaults(tool) {
  var style = Core__Option.flatMap(tool, getStyle);
  if (style !== undefined) {
    return style;
  } else {
    return defaultStyle;
  }
}

function getLineWidth(style) {
  return Core__Option.getOr(style.lineWidth, Canvas__Style.elementLineWidth);
}

var CanvasStyle;

export {
  CanvasStyle ,
  defaultStyle ,
  getStyle ,
  getOptStyleWithDefaults ,
  getLineWidth ,
}
/* No side effect */
