// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";
import * as Canvas__Experimental__StateUtils from "./Canvas__Experimental__StateUtils.bs.js";
import * as Canvas__Experimental__ElementUtils from "../Canvas__Experimental__ElementUtils.bs.js";

var tool_engine = {
  TAG: "Line",
  _0: {
    canResizeStart: true,
    canResizeEnd: true
  }
};

function tool_onStart(param) {
  var match = param.store;
  var snapToGrid = match.snapToGrid;
  var clientY = param.clientY;
  var clientX = param.clientX;
  var state = Canvas__Experimental__StateUtils.getLineState(match.state);
  var match$1;
  if (typeof snapToGrid !== "object") {
    match$1 = [
      clientX,
      clientY
    ];
  } else {
    var gridSize = snapToGrid._0;
    match$1 = [
      Canvas__Experimental__ElementUtils.roundNumberBySnapGridSize(clientX, gridSize),
      Canvas__Experimental__ElementUtils.roundNumberBySnapGridSize(clientY, gridSize)
    ];
  }
  if (state === undefined) {
    return ;
  }
  var y = match$1[1];
  var x = match$1[0];
  if (state !== "Idle") {
    return ;
  }
  var element = {
    TAG: "Line",
    _0: {
      id: Uuid.v4(),
      toolId: match.selectedToolId,
      zIndex: param.nextIndex,
      label: undefined,
      start: {
        x: x,
        y: y
      },
      end: {
        x: x,
        y: y
      }
    }
  };
  param.updateStore(function (prev) {
        return {
                state: {
                  TAG: "Line",
                  _0: "Drawing"
                },
                snapToGrid: prev.snapToGrid,
                selectedToolId: prev.selectedToolId,
                selectedElementIds: prev.selectedElementIds,
                elements: prev.elements.concat([element])
              };
      });
}

function tool_onMove(param) {
  var match = param.store;
  var elements = match.elements;
  var state = Canvas__Experimental__StateUtils.getLineState(match.state);
  var position = elements.length - 1 | 0;
  var element = elements[position];
  if (state === undefined) {
    return ;
  }
  if (state === "Idle") {
    param.target.style.cursor = "crosshair";
    return ;
  }
  if (element === undefined) {
    return ;
  }
  if (element.TAG !== "Line") {
    return ;
  }
  var line = element._0;
  var element$1 = {
    TAG: "Line",
    _0: {
      id: line.id,
      toolId: line.toolId,
      zIndex: line.zIndex,
      label: line.label,
      start: line.start,
      end: {
        x: param.clientX,
        y: param.clientY
      }
    }
  };
  param.updateStore(function (prev) {
        return {
                state: prev.state,
                snapToGrid: prev.snapToGrid,
                selectedToolId: prev.selectedToolId,
                selectedElementIds: prev.selectedElementIds,
                elements: Canvas__Experimental__ElementUtils.updateElementAtPosition(prev.elements, position, element$1)
              };
      });
}

function tool_onEnd(param) {
  var updateStore = param.updateStore;
  var match = param.store;
  var elements = match.elements;
  var snapToGrid = match.snapToGrid;
  var state = Canvas__Experimental__StateUtils.getLineState(match.state);
  if (state === undefined) {
    return ;
  }
  if (typeof snapToGrid !== "object") {
    return updateStore(function (prev) {
                return {
                        state: {
                          TAG: "Line",
                          _0: "Idle"
                        },
                        snapToGrid: prev.snapToGrid,
                        selectedToolId: prev.selectedToolId,
                        selectedElementIds: [],
                        elements: prev.elements
                      };
              });
  }
  var position = elements.length - 1 | 0;
  var element = elements[position];
  if (element === undefined) {
    return updateStore(function (prev) {
                return {
                        state: {
                          TAG: "Rect",
                          _0: "Idle"
                        },
                        snapToGrid: prev.snapToGrid,
                        selectedToolId: prev.selectedToolId,
                        selectedElementIds: [],
                        elements: prev.elements
                      };
              });
  }
  var element$1 = Canvas__Experimental__ElementUtils.snapElementToGrid(element, snapToGrid._0);
  updateStore(function (prev) {
        return {
                state: {
                  TAG: "Line",
                  _0: "Idle"
                },
                snapToGrid: prev.snapToGrid,
                selectedToolId: prev.selectedToolId,
                selectedElementIds: [],
                elements: Canvas__Experimental__ElementUtils.updateElementAtPosition(prev.elements, position, element$1)
              };
      });
}

var tool = {
  toolId: "line",
  engine: tool_engine,
  onStart: tool_onStart,
  onMove: tool_onMove,
  onEnd: tool_onEnd
};

var ElementUtils;

var SelectionUtils;

var StateUtils;

export {
  ElementUtils ,
  SelectionUtils ,
  StateUtils ,
  tool ,
}
/* uuid Not a pure module */
