name: "Analyze yarn.lock changes"

on:
  pull_request:

jobs:
  analyze_yarn_lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          collapsibleThreshold: "25"
          path: "/yarn.lock"
          token: ${{ secrets.GITHUB_TOKEN }}
          updateComment: "true"
